# Generated by Django 5.0.6 on 2024-07-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_phone_contact_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='phonenumber',
        ),
    ]
