# Generated by Django 5.0.6 on 2024-08-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_internship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('proj_category', models.CharField(max_length=80)),
                ('client', models.CharField(max_length=80)),
                ('proj_date', models.DateField(auto_now=True)),
                ('proj_url', models.CharField(max_length=200)),
                ('proj_detail', models.TextField()),
            ],
        ),
    ]
