# Generated by Django 5.0.6 on 2024-08-07 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='project_details',
            name='proj_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.category'),
        ),
    ]
