# Generated by Django 5.0.6 on 2024-08-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_category_alter_project_details_proj_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_details',
            name='proj_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
