# Generated by Django 5.0.6 on 2024-08-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_project_details_proj_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog',
            field=models.TextField(default=''),
        ),
    ]
